smf:
  sbi:
    server:
      - address: 172.20.0.5
        port: 7777
    client:
      nrf:
        - uri: http://172.20.0.3:7777

  pfcp:
    server:
      - address: 172.20.0.5
    client:
      upf:
        - address: 172.20.0.7 #UPF EMBB
          dnn: internet
        - address: 172.20.0.8 #UPF uRLLC
          dnn: internet2

  gtpu:
    server:
      - address: 172.20.0.5

  dns:
    - 8.8.8.8
    - 8.8.4.4

  mtu: 1400

  session:
  - dnn: internet
    subnet: 10.45.0.0/16
    gateway: 10.45.0.1
  - dnn: internet2
    subnet: 10.46.0.0/16
    gateway: 10.46.0.254
