udr:
  sbi:
    server:
      - dev: eth0
        port: 7777
    client:
      nrf:
        - uri: http://nrf:7777
  mongodb:
    name: open5gs
    url: mongodb://mongo:27017/open5gs
  logger:
    level: info
  global:
    max:
      ue: 2048
