upf:
  pfcp:
    server:
      - dev: eth0
  gtpu:
    server:
      - dev: eth0
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: internet2
  metrics:
    server:
      - dev: eth0
        port: 9090
  logger:
    level: info
